import type { Metadata } from 'next';
import '../styles/vendor/normalize.css';
import '../styles/site/globals.css';
import '../styles/site/variables.css';
import '../styles/site/base.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body>{children}</body>
    </html>
  )
}
