// import type { Metadata } from 'next';
// import '../styles/vendor/normalize.css';
import localFont from "next/font/local";
import "../styles/site/global.css";

const myFont = localFont({
  src: [
    {
      path: "../styles/fonts/montserrat/Montserrat-Light.woff2",
      weight: "300",
      style: "normal",
    
    },
    {
      path: "../styles/fonts/montserrat/Montserrat-Regular.woff2",
      weight: "normal",
      style: "normal",
    },
    {
      path: "../styles/fonts/montserrat/Montserrat-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../styles/fonts/montserrat/Montserrat-Bold.woff2",
      weight: "bold",
      style: "normal",
    },
  ],
  display: 'swap',
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <head>
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
      </head>
      <body className={myFont.className}>{children}</body>
    </html>
  );
}
